// Main application logic for the ICVC redemption SPA.
// Loads runtime configuration from ./config.js (generated by deploy.sh from
// config.js.template) and IDL factories from ./idl.js. The @dfinity packages
// are loaded dynamically from ./dfinity.js (a checked-in browser bundle).

import { CONFIG, E8S } from "./config.js";
import { buildIdlFactories } from "./idl.js";

const { HttpAgent, Actor, AuthClient, IDL, Principal } = await import("./dfinity.js");
const { ledgerIdl, redemptionIdl, icpLegacyIdl } = buildIdlFactories(IDL);

// ============================================================
// State
// ============================================================
let authClient = null;
let agent = null;
let userPrincipal = null;
let icvcLedger = null;
let icpLedger = null;
let redemption = null;
let icpLegacy = null;   // ICP ledger via its legacy (account-identifier) transfer interface
let balances = { icvc: 0n, icp: 0n };
let exchangeRate = CONFIG.EXCHANGE_RATE;
let paused = false;   // mirrors the canister's server-side pause (from getStats)

// ============================================================
// Helpers
// ============================================================
function e8sToDisplay(e8s, decimals) {
  if (typeof e8s !== "bigint") e8s = BigInt(e8s);
  if (decimals !== undefined) {
    // Always show exactly `decimals` places (so whole amounts read "60.00",
    // not "60") — keeps balances aligned across ICVC / ICP / Send.
    return (Number(e8s) / 1e8).toLocaleString(undefined, {
      minimumFractionDigits: decimals,
      maximumFractionDigits: decimals,
    });
  }
  const whole = e8s / E8S;
  const frac = e8s % E8S;
  const fracStr = frac.toString().padStart(8, "0").replace(/0+$/, "");
  if (!fracStr) return whole.toLocaleString();
  return whole.toLocaleString() + "." + fracStr;
}

function e8sToInput(e8s) {
  if (typeof e8s !== "bigint") e8s = BigInt(e8s);
  const whole = e8s / E8S;
  const frac = e8s % E8S;
  const fracStr = frac.toString().padStart(8, "0").replace(/0+$/, "");
  if (!fracStr) return whole.toString();
  return whole.toString() + "." + fracStr;
}

function tokenToE8s(s) {
  s = s.replace(/,/g, "");
  const parts = s.split(".");
  const whole = BigInt(parts[0] || "0") * E8S;
  if (parts.length === 1) return whole;
  const frac = (parts[1] || "0").padEnd(8, "0").slice(0, 8);
  return whole + BigInt(frac);
}

function shortenPrincipal(p) {
  if (p.length <= 15) return p;
  return p.slice(0, 5) + "..." + p.slice(-5);
}

function timeAgo(nsTimestamp) {
  const ms = Number(BigInt(nsTimestamp) / 1_000_000n);
  const seconds = Math.floor((Date.now() - ms) / 1000);
  if (seconds < 60) return "just now";
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days < 30) return `${days}d ago`;
  return new Date(ms).toLocaleDateString(undefined, { month: "short", day: "numeric" });
}

function updateRedeemButton() {
  const btn = $("btn-redeem");
  if (paused) { btn.disabled = true; btn.textContent = "Redemptions paused"; return; }
  if (!userPrincipal) { btn.disabled = true; btn.textContent = "Login to redeem"; return; }
  const raw = $("icvc-input").value;
  const hasAmount = raw && !isNaN(parseFloat(raw)) && parseFloat(raw) > 0;
  btn.disabled = !hasAmount;
  btn.textContent = "Redeem ICVC for ICP";
}

function $(id) { return document.getElementById(id); }

function showMsg(id, text, isError) {
  const el = $(id);
  el.className = "msg " + (isError ? "msg-error" : "msg-success");
  el.textContent = text;
  el.classList.remove("hidden");
}
function hideMsg(id) { $(id).className = "hidden"; }

// Count-up animation
function animateCountUp(element, targetValue, duration) {
  const start = performance.now();
  const startValue = parseFloat(element.textContent.replace(/,/g, "")) || 0;
  const diff = targetValue - startValue;
  if (Math.abs(diff) < 0.01) {
    element.textContent = targetValue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    return;
  }
  function tick(now) {
    const elapsed = now - start;
    const progress = Math.min(elapsed / duration, 1);
    // Ease-out cubic
    const eased = 1 - Math.pow(1 - progress, 3);
    const current = startValue + diff * eased;
    element.textContent = current.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    if (progress < 1) requestAnimationFrame(tick);
  }
  requestAnimationFrame(tick);
}

// ============================================================
// Tab switching
// ============================================================
window.showTab = function(tab) {
  $("view-swap").classList.toggle("hidden", tab !== "swap");
  $("view-wallet").classList.toggle("hidden", tab !== "wallet");
  $("tab-swap").classList.toggle("active", tab === "swap");
  $("tab-wallet").classList.toggle("active", tab === "wallet");
  if (tab === "wallet") refreshWallet();
};

// ============================================================
// Auth
// ============================================================
async function initAuth() {
  authClient = await AuthClient.create();
  if (await authClient.isAuthenticated()) {
    await setupAgent(authClient.getIdentity());
  }
}

async function setupAgent(identity) {
  agent = await HttpAgent.create({ host: CONFIG.HOST, identity });
  if (CONFIG.HOST.includes("127.0.0.1")) { await agent.fetchRootKey(); }
  userPrincipal = identity.getPrincipal();

  icvcLedger = Actor.createActor(ledgerIdl, { agent, canisterId: CONFIG.ICVC_LEDGER_ID });
  icpLedger  = Actor.createActor(ledgerIdl, { agent, canisterId: CONFIG.ICP_LEDGER_ID });
  icpLegacy  = Actor.createActor(icpLegacyIdl, { agent, canisterId: CONFIG.ICP_LEDGER_ID });
  redemption = Actor.createActor(redemptionIdl, { agent, canisterId: CONFIG.REDEMPTION_ID });

  $("principal-text").textContent = shortenPrincipal(userPrincipal.toText());
  $("principal-display").classList.remove("hidden");
  $("btn-connect").classList.add("hidden");
  $("btn-disconnect").classList.remove("hidden");
  // Surface the per-origin principal + "send your ICVC here first" guidance:
  // the logged-in principal must HOLD the ICVC for redeem to work.
  const spNote = $("send-path-note");
  if (spNote) { $("send-path-principal-text").textContent = shortenPrincipal(userPrincipal.toText()); spNote.classList.remove("hidden"); }
  updateRedeemButton();

  await refreshBalances();
  await refreshStats();
  await refreshWallet();
}

window.copyPrincipal = async function(tooltipId) {
  if (!userPrincipal) return;
  try {
    await navigator.clipboard.writeText(userPrincipal.toText());   // always the FULL principal
    const tooltip = $(tooltipId || "copied-tooltip");
    if (tooltip) {
      tooltip.classList.add("show");
      setTimeout(() => tooltip.classList.remove("show"), 1500);
    }
  } catch (err) {
    console.error("Copy failed:", err);
  }
};

// Toggle the exchange-rate derivation panel. Values are filled by refreshStats
// from getFairValueInputs; this just shows/hides and tracks aria-expanded.
window.toggleRateInfo = function() {
  const nowHidden = $("rate-info-panel").classList.toggle("hidden");
  $("rate-info-btn").setAttribute("aria-expanded", String(!nowHidden));
};

window.handleConnect = async function() {
  if (!authClient) return;
  const loginOptions = {
    identityProvider: CONFIG.II_PROVIDER,
    onSuccess: async () => {
      await setupAgent(authClient.getIdentity());
    },
    onError: (err) => {
      console.error("Login failed:", err);
    },
  };
  // Standard per-origin II: the user gets a principal scoped to THIS dapp's
  // origin. We deliberately do NOT set derivationOrigin — that would give this
  // frontend the user's identity at another origin, i.e. authority over the
  // assets that identity controls there, not just ICVC. Holders send their
  // ICVC to their per-origin principal first (see the send-path note).
  await authClient.login(loginOptions);
};

window.handleDisconnect = async function() {
  if (!authClient) return;
  await authClient.logout();
  agent = null; userPrincipal = null; icvcLedger = null; icpLedger = null; redemption = null;
  balances = { icvc: 0n, icp: 0n };
  $("principal-text").textContent = "";
  $("principal-display").classList.add("hidden");
  $("btn-connect").classList.remove("hidden");
  $("btn-disconnect").classList.add("hidden");
  $("send-path-note")?.classList.add("hidden");
  $("swap-icvc-balance").textContent = "0";
  updateOutput();
  updateRedeemButton();
};

// ============================================================
// Balances
// ============================================================
async function refreshBalances() {
  if (!icvcLedger || !userPrincipal) return;
  try {
    const account = { owner: userPrincipal, subaccount: [] };
    const [icvc, icp] = await Promise.all([
      icvcLedger.icrc1_balance_of(account),
      icpLedger.icrc1_balance_of(account),
    ]);
    balances = { icvc: BigInt(icvc), icp: BigInt(icp) };
    $("swap-icvc-balance").textContent = e8sToDisplay(balances.icvc);
    updateRedeemButton();
  } catch (err) {
    console.error("Balance fetch failed:", err);
  }
}

// ============================================================
// Stats
// ============================================================
async function refreshStats() {
  try {
    let a = agent;
    if (!a) {
      a = await HttpAgent.create({ host: CONFIG.HOST });
      if (CONFIG.HOST.includes("127.0.0.1")) { await a.fetchRootKey(); }
    }
    const r = Actor.createActor(redemptionIdl, { agent: a, canisterId: CONFIG.REDEMPTION_ID });
    const [s, history, fv] = await Promise.all([
      r.getStats(),
      r.getRedemptionHistory(0n, 10n),
      r.getFairValueInputs(),
    ]);

    const distributed = BigInt(s.total_icp_distributed);
    const remaining = BigInt(s.icp_remaining);
    exchangeRate = BigInt(s.exchange_rate_e8s);

    // Replace spinner with value and animate
    const heroContainer = $("hero-container");
    let heroEl = $("hero-icp-distributed");
    if (!heroEl) {
      heroContainer.innerHTML = '<span class="hero-value" id="hero-icp-distributed">0</span><span class="hero-suffix">ICP</span>';
      heroEl = $("hero-icp-distributed");
    }
    animateCountUp(heroEl, Number(distributed) / 1e8, 1500);

    // Progress bar = wind-down progress: ICVC redeemed / original supply. This
    // is monotonic and immune to ICP pool top-ups (unlike distributed/pool,
    // whose denominator grows on every top-up and makes the bar move backwards).
    const redeemedIcvc = BigInt(s.total_icvc_redeemed);
    const supplyIcvc = BigInt(fv.icvc_total_supply_e8s);
    const windDownPct = supplyIcvc > 0n ? Number(redeemedIcvc * 1000000n / supplyIcvc) / 10000 : 0;
    $("stat-icvc-redeemed-progress").textContent = e8sToDisplay(redeemedIcvc, 2);
    $("stat-icvc-supply").textContent = e8sToDisplay(supplyIcvc, 2);
    $("stat-percent").textContent = windDownPct.toFixed(2);
    $("progress-fill").style.width = windDownPct + "%";
    // Current ICP pool size = the canister's live ICP balance (what's available
    // to pay redemptions). The hero shows cumulative distributed separately.
    $("stat-pool").textContent = e8sToDisplay(remaining, 2);
    $("stat-icvc-redeemed").textContent = e8sToDisplay(BigInt(s.total_icvc_redeemed), 2);
    $("stat-count").textContent = s.total_redemptions.toString();
    $("stat-status").textContent = s.paused ? "Paused" : "Active";
    $("stat-status").style.color = s.paused ? "#fca5a5" : "#86efac";
    // Surface the real, server-side gate: when the canister is paused, show the
    // banner and disable redeeming (redeem would return #Paused anyway).
    paused = s.paused;
    $("paused-banner")?.classList.toggle("hidden", !paused);
    updateRedeemButton();
    $("exchange-rate").textContent = (Number(exchangeRate) / 1e8).toFixed(8);

    // Exchange-rate derivation panel (toggled by the ℹ button next to the rate).
    $("fv-supply").textContent = e8sToDisplay(BigInt(fv.icvc_total_supply_e8s), 2) + " ICVC";
    $("fv-icp").textContent = e8sToDisplay(BigInt(fv.treasury_icp_e8s), 2) + " ICP";
    $("fv-nicp").textContent = e8sToDisplay(BigInt(fv.treasury_nicp_e8s), 2) + " nICP";
    $("fv-nicp-icp").textContent = e8sToDisplay(BigInt(fv.nicp_as_icp_e8s), 2) + " ICP";
    $("fv-backing").textContent = e8sToDisplay(BigInt(fv.backing_icp_e8s), 2) + " ICP";
    $("fv-rate").textContent = (Number(exchangeRate) / 1e8).toFixed(8) + " ICP";
    // inputs_recorded_at is nanoseconds since epoch; show the UTC date.
    $("fv-date").textContent =
      new Date(Number(BigInt(fv.inputs_recorded_at) / 1000000n)).toISOString().slice(0, 10);

    renderTxList("global-tx-list", history);
  } catch (err) {
    console.error("Stats fetch failed:", err);
  }
}

// Build a single `<span>` with `class` and text content. Used by
// renderTxList; keeps everything text-only so no interpolation can
// ever introduce HTML or script content.
function makeSpan(cls, text) {
  const span = document.createElement("span");
  span.className = cls;
  span.textContent = text;
  return span;
}

function renderTxList(elementId, records) {
  const el = $(elementId);
  el.replaceChildren();  // clear without using innerHTML
  if (!records || records.length === 0) {
    el.appendChild(makeSpan("empty", "No redemptions yet."));
    return;
  }
  for (const r of records) {
    const item = document.createElement("div");
    item.className = "tx-item";

    const left = document.createElement("div");
    left.className = "tx-left";
    left.appendChild(makeSpan("tx-id", `#${r.id}`));
    left.appendChild(makeSpan("tx-principal", shortenPrincipal(r.user.toText())));
    left.appendChild(makeSpan("tx-time", timeAgo(r.timestamp)));

    const right = document.createElement("div");
    right.className = "tx-right";
    right.appendChild(makeSpan("tx-icvc", `-${e8sToDisplay(BigInt(r.icvc_amount), 2)} ICVC`));
    right.appendChild(makeSpan("tx-icp", `+${e8sToDisplay(BigInt(r.icp_amount), 2)} ICP`));

    item.appendChild(left);
    item.appendChild(right);
    el.appendChild(item);
  }
}

// ============================================================
// Swap
// ============================================================
function formatInputWithCommas(input) {
  const cursorPos = input.selectionStart;
  const oldVal = input.value;
  const stripped = oldVal.replace(/,/g, "");
  const parts = stripped.split(".");
  const formatted = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ",") + (parts.length > 1 ? "." + parts[1] : "");
  if (formatted !== oldVal) {
    const commasBefore = (oldVal.slice(0, cursorPos).match(/,/g) || []).length;
    input.value = formatted;
    const commasAfter = (formatted.slice(0, cursorPos + (formatted.length - oldVal.length)).match(/,/g) || []).length;
    input.selectionStart = input.selectionEnd = cursorPos + (commasAfter - commasBefore);
  }
}

window.updateOutput = function() {
  const input = $("icvc-input");
  formatInputWithCommas(input);
  const raw = input.value;
  updateRedeemButton();
  if (!raw || isNaN(parseFloat(raw.replace(/,/g, "")))) {
    $("icp-output").textContent = "0.00";
    return;
  }
  try {
    const icvcE8s = tokenToE8s(raw);
    const icpE8s = (icvcE8s * exchangeRate) / E8S;
    $("icp-output").textContent = e8sToDisplay(icpE8s);
  } catch {
    $("icp-output").textContent = "0.00";
  }
};

window.setMax = async function() {
  if (balances.icvc <= 0n) return;
  // The user needs to keep 2 × ledger fee aside (approve + transfer_from).
  // MAX redeems whatever's left after both fees are reserved.
  let icvcFee = 10_000n;
  try {
    if (icvcLedger) icvcFee = BigInt(await icvcLedger.icrc1_fee());
  } catch {}
  const redeemable = balances.icvc - icvcFee * 2n;
  if (redeemable <= 0n) return;
  $("icvc-input").value = e8sToInput(redeemable);
  updateOutput();
};

// Show confirmation modal instead of directly redeeming
// Mirrors MIN_REDEMPTION in src/redemption/main.mo. Client-side check is
// purely UX (the canister body re-validates and returns #BelowMinimum if
// bypassed).
const MIN_REDEMPTION_E8S = 10n * 100_000_000n;

window.handleRedeem = async function() {
  if (!redemption || !icvcLedger || !userPrincipal) return;
  const raw = $("icvc-input").value;
  if (!raw) return;
  const icvcE8s = tokenToE8s(raw);
  if (icvcE8s <= 0n) return;
  hideMsg("redeem-msg");
  if (icvcE8s < MIN_REDEMPTION_E8S) {
    showMsg("redeem-msg", `Minimum redemption is ${e8sToDisplay(MIN_REDEMPTION_E8S, 2)} ICVC. You entered ${e8sToDisplay(icvcE8s, 2)} ICVC.`, true);
    return;
  }
  await refreshBalances();
  if (balances.icvc < icvcE8s) {
    showMsg("redeem-msg", `Insufficient balance: you have ${e8sToDisplay(balances.icvc)} ICVC but tried to redeem ${e8sToDisplay(icvcE8s)} ICVC. Click MAX to use your full balance.`, true);
    return;
  }
  const icpE8s = (icvcE8s * exchangeRate) / E8S;
  // Pull the live ICVC ledger fee so the modal reflects what the approve +
  // transfer_from will actually cost.
  const icvcFee = BigInt(await icvcLedger.icrc1_fee());
  $("confirm-icvc").textContent = e8sToDisplay(icvcE8s, 2) + " ICVC";
  $("confirm-fees").textContent = e8sToDisplay(icvcFee * 2n, 8) + " ICVC";
  $("confirm-icp").textContent = e8sToDisplay(icpE8s, 2) + " ICP";
  // Populate the rate from the live exchange rate (fair-value derived; changes
  // via canister upgrade) rather than a hardcoded literal, so it always matches
  // the You-receive amount computed just above.
  $("confirm-rate").textContent = "1 ICVC = " + (Number(exchangeRate) / 1e8).toFixed(8) + " ICP";
  openConfirmModal();
};

// Tracks the element that had focus before the modal opened, so we can
// return focus there on close (WCAG 2.4.3).
let modalReturnFocus = null;

function openConfirmModal() {
  modalReturnFocus = document.activeElement;
  $("confirm-modal").classList.remove("hidden");
  // Initial focus goes to Cancel — the safer default for an action that
  // commits funds.
  $("btn-cancel-redeem").focus();
}

window.closeConfirmModal = function() {
  $("confirm-modal").classList.add("hidden");
  if (modalReturnFocus && typeof modalReturnFocus.focus === "function") {
    modalReturnFocus.focus();
  }
  modalReturnFocus = null;
};

// Modal keyboard handling: Escape closes; Tab cycles within the modal so
// focus can't escape into the form behind it.
document.addEventListener("keydown", (e) => {
  const modal = $("confirm-modal");
  if (modal.classList.contains("hidden")) return;

  if (e.key === "Escape") {
    e.preventDefault();
    window.closeConfirmModal();
    return;
  }

  if (e.key !== "Tab") return;
  const focusables = modal.querySelectorAll("button:not([disabled])");
  if (focusables.length === 0) return;
  const first = focusables[0];
  const last = focusables[focusables.length - 1];
  if (e.shiftKey && document.activeElement === first) {
    e.preventDefault();
    last.focus();
  } else if (!e.shiftKey && document.activeElement === last) {
    e.preventDefault();
    first.focus();
  }
});

window.confirmRedeem = async function() {
  const raw = $("icvc-input").value;
  if (!raw) return;
  const icvcE8s = tokenToE8s(raw);
  if (icvcE8s <= 0n) return;

  hideMsg("redeem-msg");
  // Disable the confirm button immediately (guards against a double-click /
  // double-submit) and show progress in the open modal, like the Send modal.
  const btn = $("btn-confirm-redeem");
  btn.disabled = true;
  btn.innerHTML = '<span class="spinner"></span>Approving ICVC...';

  try {
    // Semantics: the input value (icvcE8s) is the amount that reaches the
    // canister. Two ICVC ledger fees are paid by the user on top: one for
    // approve, one absorbed by transfer_from (paid by the `from` account
    // per ICRC-2). The user needs `icvcE8s + 2 × fee` of balance, and the
    // approval allowance must cover `icvcE8s + fee` (the transfer_from cost).
    const fee = BigInt(await icvcLedger.icrc1_fee());
    await refreshBalances();
    const totalIcvcOutflow = icvcE8s + fee * 2n;
    if (balances.icvc < totalIcvcOutflow) {
      throw new Error(`Insufficient balance: redeeming ${e8sToDisplay(icvcE8s)} ICVC costs ${e8sToDisplay(totalIcvcOutflow)} ICVC including ledger fees, but you have ${e8sToDisplay(balances.icvc)} ICVC.`);
    }

    const approveResult = await icvcLedger.icrc2_approve({
      from_subaccount: [], spender: { owner: Principal.fromText(CONFIG.REDEMPTION_ID), subaccount: [] },
      amount: icvcE8s + fee, expected_allowance: [], expires_at: [],
      fee: [], memo: [], created_at_time: [],
    });
    if ("Err" in approveResult) throw new Error("Approve failed: " + JSON.stringify(approveResult.Err));

    btn.innerHTML = '<span class="spinner"></span>Redeeming...';
    const result = await redemption.redeem(icvcE8s);
    if ("err" in result) {
      const key = Object.keys(result.err)[0];
      throw new Error("Redeem failed: " + key + (result.err[key] !== null ? " - " + result.err[key] : ""));
    }

    closeConfirmModal();
    showMsg("redeem-msg", "Redemption successful!", false);
    $("icvc-input").value = "";
    updateOutput();
    await refreshBalances();
    await refreshStats();
  } catch (err) {
    closeConfirmModal();
    showMsg("redeem-msg", err.message || "Unknown error", true);
    await refreshBalances();
  } finally {
    btn.textContent = "Confirm Swap";
    btn.disabled = false;
    updateRedeemButton();
  }
};

// ============================================================
// Wallet tab
// ============================================================
async function refreshWallet() {
  if (!userPrincipal) {
    $("wallet-connect-prompt").classList.remove("hidden");
    $("wallet-content").classList.add("hidden");
    return;
  }
  $("wallet-connect-prompt").classList.add("hidden");
  $("wallet-content").classList.remove("hidden");

  await refreshBalances();
  $("wallet-icvc").textContent = e8sToDisplay(balances.icvc, 2);
  $("wallet-icp").textContent = e8sToDisplay(balances.icp, 2);
  onSendTokenChange();   // refresh the Send card's balance line for the selected token

  try {
    // Show the most recent 50 redemptions for this user; the canister
    // method is paginated (offset, limit) per M1 to keep responses bounded.
    const txs = await redemption.getUserRedemptions(userPrincipal, 0n, 50n);
    renderTxList("user-tx-list", txs);
  } catch (err) {
    console.error("User tx fetch failed:", err);
  }
}

// ============================================================
// Send (withdraw ICP / ICVC from the per-origin principal)
// ============================================================
// CRC32 (IEEE) — validates an ICP account-identifier's 4-byte checksum.
function crc32(bytes) {
  let crc = 0xFFFFFFFF;
  for (let i = 0; i < bytes.length; i++) {
    crc ^= bytes[i];
    for (let j = 0; j < 8; j++) crc = (crc & 1) ? ((crc >>> 1) ^ 0xEDB88320) : (crc >>> 1);
  }
  return (crc ^ 0xFFFFFFFF) >>> 0;
}

// Parse a 64-hex ICP account identifier into 32 bytes, verifying its CRC32
// checksum (first 4 bytes) so a mistyped address is caught before sending.
function accountIdFromHex(hex) {
  hex = hex.trim().toLowerCase();
  if (!/^[0-9a-f]{64}$/.test(hex)) throw new Error("ICP account ID must be 64 hex characters.");
  const bytes = [];
  for (let i = 0; i < 64; i += 2) bytes.push(parseInt(hex.substr(i, 2), 16));
  const want = crc32(bytes.slice(4));
  const got = ((bytes[0] << 24) | (bytes[1] << 16) | (bytes[2] << 8) | bytes[3]) >>> 0;
  if (want !== got) throw new Error("ICP account ID checksum failed — double-check the address.");
  return bytes;
}

window.onSendTokenChange = function() {
  const tok = $("send-token").value;
  $("send-balance-sym").textContent = tok;
  $("send-balance").textContent = e8sToDisplay(tok === "ICVC" ? balances.icvc : balances.icp, 4);
  // ICVC (ICRC-1) goes to a principal; ICP may also go to a 64-hex account id.
  const isIcp = tok === "ICP";
  if ($("send-to-label")) $("send-to-label").textContent = isIcp ? "ICP account ID (address)" : "Recipient principal";
  if ($("send-to")) $("send-to").placeholder = isIcp ? "64-character ICP account ID" : "recipient principal";
  updateSendButton();
};

window.setSendMax = async function() {
  const tok = $("send-token").value;
  const ledger = tok === "ICVC" ? icvcLedger : icpLedger;
  if (!ledger) return;
  try {
    const fee = BigInt(await ledger.icrc1_fee());
    const bal = tok === "ICVC" ? balances.icvc : balances.icp;
    $("send-amount").value = e8sToInput(bal > fee ? bal - fee : 0n);
  } catch (err) { console.error("fee fetch failed:", err); }
  updateSendButton();
};

window.updateSendButton = function() {
  const btn = $("btn-send");
  if (!btn) return;
  const to = $("send-to").value.trim();
  const raw = $("send-amount").value;
  const amountOk = raw && !isNaN(parseFloat(raw)) && parseFloat(raw) > 0;
  btn.disabled = !(to.length > 0 && amountOk);
};

let pendingSend = null;          // staged by handleSend, executed by confirmSend
let sendModalReturnFocus = null;

window.handleSend = async function() {
  hideMsg("send-msg");
  const tok = $("send-token").value;
  const ledger = tok === "ICVC" ? icvcLedger : icpLedger;
  const bal = tok === "ICVC" ? balances.icvc : balances.icp;
  if (!ledger) { showMsg("send-msg", "Not connected.", true); return; }
  const toText = $("send-to").value.trim();

  // Resolve the destination. ICVC (ICRC-1) -> principal. ICP -> a 64-hex
  // account identifier (the address format used everywhere for ICP), sent via
  // the ledger's legacy `transfer`.
  let mode = null, toPrincipal = null, toAccount = null;
  if (tok === "ICP") {
    try { toAccount = accountIdFromHex(toText); mode = "accountid"; }
    catch (e) { showMsg("send-msg", e.message, true); return; }
  } else {
    try { toPrincipal = Principal.fromText(toText); mode = "principal"; }
    catch { showMsg("send-msg", "Enter a valid recipient principal.", true); return; }
  }

  let amt;
  try { amt = tokenToE8s($("send-amount").value); }
  catch { showMsg("send-msg", "Invalid amount.", true); return; }
  if (amt <= 0n) { showMsg("send-msg", "Enter an amount greater than 0.", true); return; }

  let fee;
  try { fee = BigInt(await ledger.icrc1_fee()); }
  catch { showMsg("send-msg", "Could not fetch the ledger fee — try again.", true); return; }
  if (amt + fee > bal) {
    showMsg("send-msg", `Insufficient ${tok}: ${e8sToDisplay(amt)} + ${e8sToDisplay(fee)} fee exceeds your ${e8sToDisplay(bal)} ${tok}.`, true);
    return;
  }

  // Stage the send and show the styled confirmation modal (same look as redeem).
  pendingSend = { tok, ledger, amt, fee, mode, toPrincipal, toAccount };
  $("send-confirm-amount").textContent = e8sToDisplay(amt) + " " + tok;
  $("send-confirm-to").textContent = toText;
  $("send-confirm-fee").textContent = e8sToDisplay(fee) + " " + tok;
  openSendModal();
};

function openSendModal() {
  sendModalReturnFocus = document.activeElement;
  $("send-modal").classList.remove("hidden");
  $("btn-cancel-send").focus();   // safer default for a fund-committing action
}

window.closeSendModal = function() {
  $("send-modal").classList.add("hidden");
  if (sendModalReturnFocus && typeof sendModalReturnFocus.focus === "function") sendModalReturnFocus.focus();
  sendModalReturnFocus = null;
};

window.confirmSend = async function() {
  if (!pendingSend) return;
  const { tok, ledger, amt, fee, mode, toPrincipal, toAccount } = pendingSend;
  const btn = $("btn-confirm-send");
  btn.disabled = true;
  btn.innerHTML = '<span class="spinner"></span>Sending...';
  try {
    let block;
    if (mode === "accountid") {
      const res = await icpLegacy.transfer({
        to: toAccount, fee: { e8s: fee }, memo: 0n,
        from_subaccount: [], created_at_time: [], amount: { e8s: amt },
      });
      if ("Err" in res) throw new Error("Transfer failed: " + JSON.stringify(res.Err));
      block = res.Ok.toString();
    } else {
      const res = await ledger.icrc1_transfer({
        to: { owner: toPrincipal, subaccount: [] },
        amount: amt, fee: [], memo: [], from_subaccount: [], created_at_time: [],
      });
      if ("Err" in res) throw new Error("Transfer failed: " + JSON.stringify(res.Err));
      block = res.Ok.toString();
    }
    closeSendModal();
    showMsg("send-msg", `Sent ${e8sToDisplay(amt)} ${tok} (block ${block}).`, false);
    $("send-amount").value = ""; $("send-to").value = "";
    await refreshWallet();
  } catch (err) {
    closeSendModal();
    showMsg("send-msg", err.message || "Send failed", true);
  } finally {
    btn.textContent = "Confirm Send";
    btn.disabled = false;
    pendingSend = null;
  }
};

// Send modal: Escape closes (matches the redeem modal's behaviour).
document.addEventListener("keydown", (e) => {
  if ($("send-modal").classList.contains("hidden")) return;
  if (e.key === "Escape") { e.preventDefault(); closeSendModal(); }
});

// ============================================================
// Sound
// ============================================================
function playKaChing() {
  try {
    const ctx = new AudioContext();
    const t = ctx.currentTime;
    // Coin hit — short bright ping
    const o1 = ctx.createOscillator();
    const g1 = ctx.createGain();
    o1.type = "sine"; o1.frequency.setValueAtTime(1200, t); o1.frequency.exponentialRampToValueAtTime(2400, t + 0.05);
    g1.gain.setValueAtTime(0.3, t); g1.gain.exponentialRampToValueAtTime(0.001, t + 0.15);
    o1.connect(g1).connect(ctx.destination); o1.start(t); o1.stop(t + 0.15);
    // Register ring
    const o2 = ctx.createOscillator();
    const g2 = ctx.createGain();
    o2.type = "sine"; o2.frequency.setValueAtTime(3200, t + 0.08);
    g2.gain.setValueAtTime(0.2, t + 0.08); g2.gain.exponentialRampToValueAtTime(0.001, t + 0.4);
    o2.connect(g2).connect(ctx.destination); o2.start(t + 0.08); o2.stop(t + 0.4);
    setTimeout(() => ctx.close(), 500);
  } catch {}
}

// ============================================================
// Init
// ============================================================
await initAuth();
await refreshStats();
